### ISSUE TITLE
Tyranny - Commander Edition doesn't get imported

### ISSUE THREAD

**Issue by Itay080** [nyash-qq/galaxy-plugin-twitch#1]
I have 90 games in my Twitch library and this is the only game which won't import.
Weirdly enough, it imports fine in Playnite

**Comment by Danyelalejandro** [comment]
Me neither. Esteemed @nyash-qq is helping us in this topic.
One of the reasons why it could not be detected is because this is a special edition of the game that is not categorized clearly neither in Steam or GOG. It is like an hybrid between the standard and the deluxe edition. It seems to be an "unique" game only available in Twitch game library.

**Comment by Itay080** [comment]
Yes, it probably has something to do with the database Galaxy 2.0 uses to search game IDs.
I tried looking at the code for the API but can't seem to find any communication with an API which they use to retrieve metadata using a game ID, they must be doing that under the hood in the closed source Galaxy 2.0.
I wonder if they're using their own DB or a public DB in which we can add the game on our own.

**Comment by nyash-qq** [comment]
A couple of questions:
1. can you find your game in `"owned_games"` response from c:\ProgramData\GOG.com\Galaxy\logs\plugin-amazon-8b831aed-dd5f-c0c5-c843-41f9751f67a2.log? 
  a. If so, what is this game's `game_id`?
  b. If it's not there, try "My Games" -> "Refresh Games" in Twitch client, then re-connect the plugin
2. have you changed platform to anything other than "amazon"?
3. are there any error/exception messages in c:\ProgramData\GOG.com\Galaxy\logs\plugin-amazon-8b831aed-dd5f-c0c5-c843-41f9751f67a2.log

**Comment by Itay080** [comment]
Hello :)
First of all - thank you very much for creating this much needed plugin!
1. I can, here is the full entry for the game
{"game_id": "4194ff96-8a00-4896-b2d3-526bf389806f", "game_title": "Tyranny - Commander Edition", "license_info": {"license_type": "SinglePurchase"}} 
2. I have not
3. Not from what I can see but I've attached the full log anyway :)
[plugin-amazon-8b831aed-dd5f-c0c5-c843-41f9751f67a2.zip](https://github.com/nyash-qq/galaxy-plugin-twitch/files/3477137/plugin-amazon-8b831aed-dd5f-c0c5-c843-41f9751f67a2.zip)

**Comment by nyash-qq** [comment]
I've reached to GOG people and it should be working by now. Either refresh the list with menu -> Refresh Integrations, or restart the GLX.

**Comment by Itay080** [comment]
I've tried refreshing, restarting and reconnecting the integration but Tyranny still won't show up.

**Comment by Danyelalejandro** [comment]
Me neither. Same result.

**Comment by Itay080** [comment]
Yup! It works now :)
Thank you @nyash-qq and thank you for letting me know @Danyelalejandro
